In [2]:
import os
os.listdir()

['.ipynb_checkpoints',
 'GetData.ipynb',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx']

In [3]:
import pandas

In [9]:
df1 = pandas.read_csv('supermarkets.csv')
df1.set_index("ID")

Address           City             State Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  
ID             
1           8  
2          15  
3          25  
4          10  
5          12  
6          20

In [12]:
df2 = pandas.read_json('supermarkets.json')
df2.set_index("ID")

Address           City Country  Employees         Name  \
ID                                                                   
1      3666 21st St  San Francisco     USA          8      Madeira   
2    735 Dolores St  San Francisco     USA         15  Bready Shop   
3       332 Hill St  San Francisco     USA         25  Super River   
4      3995 23rd St  San Francisco     USA         10   Ben's Shop   
5   1056 Sanchez St  San Francisco     USA         12      Sanchez   
6   551 Alvarado St  San Francisco     USA         20   Richvalley   

               State  
ID                    
1           CA 94114  
2           CA 94119  
3   California 94114  
4           CA 94114  
5         California  
6           CA 94114

In [18]:
df3 = pandas.read_excel("supermarkets.xlsx", sheetname=0)
df3.set_index("ID")

Address           City             State Country Supermarket Name  \
ID                                                                              
1      3666 21st St  San Francisco          CA 94114     USA          Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA      Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA      Super River   
4      3995 23rd St  San Francisco          CA 94114     USA       Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA          Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA       Richvalley   

    Number of Employees  
ID                       
1                     8  
2                    15  
3                    25  
4                    10  
5                    12  
6                    20

In [19]:
df4 = pandas.read_csv('supermarkets-commas.txt')
df4

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [29]:
df5 = pandas.read_csv('supermarkets-semi-colons.txt', sep = ';')
df5

ID          Address           City             State Country          Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA       Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA   Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA   Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA    Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA       Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA    Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [34]:
df6 = pandas.read_json('supermarkets.json')
df6.set_index("Address")

City Country  Employees  ID         Name  \
Address                                                              
3666 21st St     San Francisco     USA          8   1      Madeira   
735 Dolores St   San Francisco     USA         15   2  Bready Shop   
332 Hill St      San Francisco     USA         25   3  Super River   
3995 23rd St     San Francisco     USA         10   4   Ben's Shop   
1056 Sanchez St  San Francisco     USA         12   5      Sanchez   
551 Alvarado St  San Francisco     USA         20   6   Richvalley   

                            State  
Address                            
3666 21st St             CA 94114  
735 Dolores St           CA 94119  
332 Hill St      California 94114  
3995 23rd St             CA 94114  
1056 Sanchez St        California  
551 Alvarado St          CA 94114

In [40]:
df6

City Country  Employees  ID         Name  \
Address                                                              
3666 21st St     San Francisco     USA          8   1      Madeira   
735 Dolores St   San Francisco     USA         15   2  Bready Shop   
332 Hill St      San Francisco     USA         25   3  Super River   
3995 23rd St     San Francisco     USA         10   4   Ben's Shop   
1056 Sanchez St  San Francisco     USA         12   5      Sanchez   
551 Alvarado St  San Francisco     USA         20   6   Richvalley   

                            State  
Address                            
3666 21st St             CA 94114  
735 Dolores St           CA 94119  
332 Hill St      California 94114  
3995 23rd St             CA 94114  
1056 Sanchez St        California  
551 Alvarado St          CA 94114

In [42]:
df6.loc["3995 23rd St":"551 Alvarado St","Employees":"State"]

Employees  ID        Name       State
Address                                               
3995 23rd St            10   4  Ben's Shop    CA 94114
1056 Sanchez St         12   5     Sanchez  California
551 Alvarado St         20   6  Richvalley    CA 94114

In [45]:
list(df6.loc[:,"Name"])

['Madeira',
 'Bready Shop',
 'Super River',
 "Ben's Shop",
 'Sanchez',
 'Richvalley']

In [51]:
df6.iloc[0:,0:]

City Country  Employees  ID         Name  \
Address                                                              
3666 21st St     San Francisco     USA          8   1      Madeira   
735 Dolores St   San Francisco     USA         15   2  Bready Shop   
332 Hill St      San Francisco     USA         25   3  Super River   
3995 23rd St     San Francisco     USA         10   4   Ben's Shop   
1056 Sanchez St  San Francisco     USA         12   5      Sanchez   
551 Alvarado St  San Francisco     USA         20   6   Richvalley   

                            State  
Address                            
3666 21st St             CA 94114  
735 Dolores St           CA 94119  
332 Hill St      California 94114  
3995 23rd St             CA 94114  
1056 Sanchez St        California  
551 Alvarado St          CA 94114

In [54]:
df6.ix[:3,:1]

City
Address                      
3666 21st St    San Francisco
735 Dolores St  San Francisco
332 Hill St     San Francisco

In [55]:
df6.drop("Country", 1)

City  Employees  ID         Name             State
Address                                                                     
3666 21st St     San Francisco          8   1      Madeira          CA 94114
735 Dolores St   San Francisco         15   2  Bready Shop          CA 94119
332 Hill St      San Francisco         25   3  Super River  California 94114
3995 23rd St     San Francisco         10   4   Ben's Shop          CA 94114
1056 Sanchez St  San Francisco         12   5      Sanchez        California
551 Alvarado St  San Francisco         20   6   Richvalley          CA 94114

In [56]:
df6

City Country  Employees  ID         Name  \
Address                                                              
3666 21st St     San Francisco     USA          8   1      Madeira   
735 Dolores St   San Francisco     USA         15   2  Bready Shop   
332 Hill St      San Francisco     USA         25   3  Super River   
3995 23rd St     San Francisco     USA         10   4   Ben's Shop   
1056 Sanchez St  San Francisco     USA         12   5      Sanchez   
551 Alvarado St  San Francisco     USA         20   6   Richvalley   

                            State  
Address                            
3666 21st St             CA 94114  
735 Dolores St           CA 94119  
332 Hill St      California 94114  
3995 23rd St             CA 94114  
1056 Sanchez St        California  
551 Alvarado St          CA 94114

In [57]:
df6.shape

(6, 6)

In [58]:
df6["Continent"] = df6.shape[0]*["North America"]

In [59]:
df6

City Country  Employees  ID         Name  \
Address                                                              
3666 21st St     San Francisco     USA          8   1      Madeira   
735 Dolores St   San Francisco     USA         15   2  Bready Shop   
332 Hill St      San Francisco     USA         25   3  Super River   
3995 23rd St     San Francisco     USA         10   4   Ben's Shop   
1056 Sanchez St  San Francisco     USA         12   5      Sanchez   
551 Alvarado St  San Francisco     USA         20   6   Richvalley   

                            State      Continent  
Address                                           
3666 21st St             CA 94114  North America  
735 Dolores St           CA 94119  North America  
332 Hill St      California 94114  North America  
3995 23rd St             CA 94114  North America  
1056 Sanchez St        California  North America  
551 Alvarado St          CA 94114  North America

In [60]:
df6["Continent"] = df6["Country"] + ", " + "North Americaaa" 

In [61]:
df6

City Country  Employees  ID         Name  \
Address                                                              
3666 21st St     San Francisco     USA          8   1      Madeira   
735 Dolores St   San Francisco     USA         15   2  Bready Shop   
332 Hill St      San Francisco     USA         25   3  Super River   
3995 23rd St     San Francisco     USA         10   4   Ben's Shop   
1056 Sanchez St  San Francisco     USA         12   5      Sanchez   
551 Alvarado St  San Francisco     USA         20   6   Richvalley   

                            State             Continent  
Address                                                  
3666 21st St             CA 94114  USA, North Americaaa  
735 Dolores St           CA 94119  USA, North Americaaa  
332 Hill St      California 94114  USA, North Americaaa  
3995 23rd St             CA 94114  USA, North Americaaa  
1056 Sanchez St        California  USA, North Americaaa  
551 Alvarado St          CA 94114  USA, North Americaaa

In [63]:
from geopy.geocoders import Nominatim

In [74]:
nom = Nominatim(scheme='http')


In [76]:
n = nom.geocode("3995 23rd Street, San Francisco, CA 94114")

In [77]:
n.latitude

37.7529648

In [78]:
n.longitude

-122.4317141

In [79]:
type(n)

geopy.location.Location

In [80]:
import pandas 
df = pandas.read_csv('supermarkets.csv')
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [81]:
df["Full Address"] = df["Address"] + ", " + df["City"] + ", " + df["State"] + ", " + df["Country"]

In [82]:
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees                                       Full Address  
0          8         3666 21st St, San Francisco, CA 94114, USA  
1         15       735 Dolores St, San Francisco, CA 94119, USA  
2         25  332 Hill St, San Francisco, California 94114, USA  
3         10         3995 23rd St, San Francisco, CA 94114, USA  
4         12    1056 Sanchez St, San Francisco, California, USA  
5         20      551 Alvarado St, San Francisco, CA 94114, USA

In [85]:
df["Coordinates"] = df["Full Address"].apply(nom.geocode)

In [86]:
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees                                       Full Address  \
0          8         3666 21st St, San Francisco, CA 94114, USA   
1         15       735 Dolores St, San Francisco, CA 94119, USA   
2         25  332 Hill St, San Francisco, California 94114, USA   
3         10         3995 23rd St, San Francisco, CA 94114, USA   
4         12    1056 Sanchez St, San Francisco, California, USA   
5         20      551 Alvarado St, San Francisco, CA 94114, USA   

                                         Coordinates  
0  (21st Street, Mission District, SF, California...  
1                                               None  
2  (Hill Street, Liberty Street Historic District...  
3  (3995, 23rd Street, Noe Valley, SF, California...  
4  (Sanchez Street, Noe Valley, SF, California, 9...  
5  (Alvarado Street, Noe Valley, SF, California, ...

In [93]:
df["Latitude"] = df["Coordinates"].apply(lambda x: x.latitude if x!= None else None)
df["Longitude"] = df["Coordinates"].apply(lambda x: x.longitude if x!= None else None)
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees                                       Full Address  \
0          8         3666 21st St, San Francisco, CA 94114, USA   
1         15       735 Dolores St, San Francisco, CA 94119, USA   
2         25  332 Hill St, San Francisco, California 94114, USA   
3         10         3995 23rd St, San Francisco, CA 94114, USA   
4         12    1056 Sanchez St, San Francisco, California, USA   
5         20      551 Alvarado St, San Francisco, CA 94114, USA   

                                         Coordinates   Latitude   Longitude  
0  (21st Street, Mission District, SF, California...  37.757429 -122.412495  
1                                               None        NaN         NaN  
2  (Hill Street, Liberty Street Historic District...  37.756102 -122.421041  
3  (3995, 23rd Street, Noe Valley, SF, California...  37.752965 -122.431714  
4  (Sanchez Street, Noe Valley, SF, California, 9...  37.748362 -122.429346  
5  (Alvarado Street, Noe Valley, SF, California, ...  37.753666 -122.434440

In [94]:
import numpy

In [98]:
list1 = [[23,42,23],[334,34],[123,3333,23,23,2]]

In [99]:
numarr = numpy.asarray(list1)

In [102]:
print(numarr)

[list([23, 42, 23]) list([334, 34]) list([123, 3333, 23, 23, 2])]


In [103]:
import cv2
im_g = cv2.imread("smallgray.png")

In [104]:
im_g = cv2.imread("smallgray.png", 0)

In [105]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [106]:
cv2.imwrite("newsmallgray.png", im_g)

True

In [107]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [108]:
im_g[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [109]:
im_g.shape

(3, 5)

In [110]:
ims = numpy.hstack((im_g,im_g))

In [111]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)